shallow_clone: true

os:
 - Visual Studio 2017

configuration:
 - Release

install:
 - cd %APPVEYOR_BUILD_FOLDER%
 - git submodule update --init --recursive
 - cd bgfx && ..\bx\tools\bin\windows\genie --with-tools vs2015

build:
  project: bgfx/.build/projects/$(TOOLSET)/bgfx.sln