shallow_clone: true

os:
 - Visual Studio 2017

configuration:
 - Release

build_script:
  - git submodule init
  - git submodule update --remote
  - cd bgfx && ..\bx\tools\bin\windows\genie --with-tools vs2015
