os:
 - Visual Studio 2017

configuration:
 - Release

install:
 - git submodule init
 - git submodule update --remote
 - cd bgfx && ..\bx\tools\bin\windows\genie --with-tools vs2015

build:
  project: .build/projects/vs2015/bgfx.sln
